version: '3.8'

services:
  db:
    image: postgres:13
    container_name: large_usernames_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - large-user-list-network  

  python:
    image: python:3.10
    container_name: python_script
    volumes:
      - ./database:/app
      - ./.env:/app/.env
    working_dir: /app
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "pip install -r requirements.txt && python migrate_users.py" ]
    networks:
      - large-user-list-network 

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - large-user-list-network

volumes:
  db_data:

networks:
  large-user-list-network:  
    driver: bridge